image: alpine/edge
triggers:
  - action: email
    condition: failure
    to: witcher <witcher@wiredspace.de>
packages:
  - go
  - rsync
secrets:
  - 3a8daec5-761a-4c5f-951f-f6463081dce2 # learningbay24 deploy
  - edda9cee-e1e4-4cd3-8096-7fc28363e0db # git.sr.ht-mirror
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no -i ~/.ssh/edda9cee-e1e4-4cd3-8096-7fc28363e0db
sources:
  - https://github.com/LearningBay24/LearningBay24-backend
tasks:
  - build: |
      cd LearningBay24-backend
      go build --ldflags '-linkmode external -extldflags "-static"'
  - test-fmt: |
      cd LearningBay24-backend
      test -z "$(find . -name '*.go' -type f | xargs gofmt -l)"
  - lint: |
      cd LearningBay24-backend
      go vet ./...
  - nopr: |
      # Don't run on GitHub PRs
      [ "$BUILD_REASON" != 'github-pr' ] || complete-build
  - mirror: |
      cd LearningBay24-backend
      git push -o skip-ci --force --mirror git@git.sr.ht:~witcher/LearningBay24-backend
  - deploy: |
      if [ "$GITHUB_REF" != "refs/heads/main" ]
      then
        echo "Skipping deploying changes if not on main branch"
        exit
      fi
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      cd LearningBay24-backend
      rsync -r ./backend migrations srht-deploy@learningbay24.de:/opt/LearningBay24-backend/
